### ISSUE TITLE
Guides roadmap

### ISSUE THREAD

**Issue by Corb3nik** [caido/doc-developer#5]
Below is the structured list of guides we'll want to add for developers.

- Frontend
  - [ ] Creating a Page
  - [ ] Creating a Command/Shortcut
  - [ ] Customizing Context Menus
  - [ ] Customizing the Command Palette
  - [ ] Communicating with the GraphQL endpoint
  - [ ] Using a Component Library
  - [ ] Using \@caido/frontend-utils

- Backend
  - [ ] Sending HTTP requests
  - [ ] Storing Plugin Data
  - [ ] Handling Events
  - [ ] Using \@caido/backend-utils

**Comment by ninjeeter** [comment]
I combined Creating a Command & Shortcut with Customizing the Command Palette. Let me know if I should split them but they went hand n hand.
